version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vorkspay
      MYSQL_DATABASE: vorkspay
      MYSQL_USER: vorkspay
      MYSQL_PASSWORD: vorkspay
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file: ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
